genesis-file="/besu_data/genesis.json"
miner-enabled=true
miner-coinbase="0xd78C987031B0256C9EA6289185E151C25EFD0e36"
rpc-http-cors-origins=["all"]
host-allowlist=["*"]
rpc-ws-enabled=true
rpc-http-enabled=true
data-path="/besu_data/data"
