on: ["push"]

name: Main Workflow

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Preinstall
        run: npm run prepare-artifacts

      - name: Install Dependencies
        run: npm install

      - name: Prettier Check
        run: npm run format:check

      - name: Solhint & Eslint Check
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build testing image
        run: docker build -t testing_image -f .github/Dockerfile .

      - name: Run tests
        run: docker run testing_image
